# Generated by Django 4.0 on 2022-01-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerservices',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
