# Generated by Django 4.0 on 2022-01-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_customerservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerservices',
        ),
    ]
