# Generated by Django 4.0 on 2022-01-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_customerservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerservices',
        ),
    ]
