# Generated by Django 4.0 on 2022-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_customerservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer Taple'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='ramallah', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='help', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='8', max_length=13),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=64),
        ),
    ]
