# Generated by Django 4.0 on 2022-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_options_remove_customer_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
