# Generated by Django 4.0 on 2022-02-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_options_service_description_and_more'),
        ('customer', '0009_alter_customer_identity_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='', max_length=24)),
                ('Status', models.BooleanField(default=False)),
                ('discount', models.CharField(default='', max_length=24)),
                ('info', models.CharField(default='', max_length=64)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
