# Generated by Django 4.0 on 2022-02-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customerservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
    ]
