# Generated by Django 3.2.10 on 2022-02-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerservice',
            options={'verbose_name': 'Customer-service'},
        ),
        migrations.RenameField(
            model_name='customerservice',
            old_name='Service',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
