# Generated by Django 3.2.10 on 2022-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220208_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
