# Generated by Django 3.2.10 on 2022-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
