# Generated by Django 4.0 on 2022-01-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('sprice', models.CharField(max_length=64)),
                ('speriod', models.CharField(max_length=64)),
            ],
        ),
    ]
