# Generated by Django 4.0 on 2022-01-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='sname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='speriod',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='sprice',
            new_name='price',
        ),
    ]
