# Generated by Django 4.0 on 2022-02-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_sname_service_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Services Taple'},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='period',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(default='', max_length=64),
        ),
    ]
