# Generated by Django 3.2.10 on 2022-02-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
    ]
