# Generated by Django 3.2.10 on 2022-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='period',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=64),
        ),
    ]
