# Generated by Django 4.0 on 2022-01-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Employee',
        ),
    ]
